INSERT INTO CAR_MODEL (ID,BRAND,CHASSIS_NUMBER,MODEL,MODEL_DETAILS,YEAR_OF_PRODUCTION) values ('10','Hyundai','123456','Verna','Details','2010');
INSERT INTO CAR_MODEL (ID,BRAND,CHASSIS_NUMBER,MODEL,MODEL_DETAILS,YEAR_OF_PRODUCTION) values ('11','Fiat','1234567','Bunto','Details','2010');
INSERT INTO CAR_MODEL (ID,BRAND,CHASSIS_NUMBER,MODEL,MODEL_DETAILS,YEAR_OF_PRODUCTION) values ('12','volkswagen','12345678','Golf','Details','2010');
INSERT INTO CAR_MODEL (ID,BRAND,CHASSIS_NUMBER,MODEL,MODEL_DETAILS,YEAR_OF_PRODUCTION) values ('13','Hyundai','133456','accent','Details','2010');
